### ISSUE TITLE
where is db connection 

### ISSUE THREAD

**Issue by graphicsxp** [madhums/node-express-mongoose-demo#101]
This application looks great and it's helpful for starting. But I can't find where the mongodb connection is actually openned. Where is it done ?

**Comment by cloud-walker** [comment]
I still have some doubts about that...

According to the [Mongoose Getting Started](http://mongoosejs.com/docs/index.html) you should listen to the 'open' connection event to ensure mongodb connection, maybe I'm missing something? Maybe the mongoose getting started is obsolete?

Thanks in advance!

**Comment by cloud-walker** [comment]
Reading the github README I have found this section: 
![screenshot from 2015-09-03 20 40 55](https://cloud.githubusercontent.com/assets/1144075/9667469/3ccf52e6-527c-11e5-9969-ca1e1fb96710.png)

Maybe I understand now :+1:
