### ISSUE TITLE
Heroku and Require Directories.

### ISSUE THREAD

**Issue by jeffj** [madhums/node-express-mongoose-demo#130]
There seems to be a problem with Heroku and not specificing the exact directory when you import JS files with node's "require". I've attached the Heroku log screenshots.

![screenshot 2015-01-20 19 54 15](https://cloud.githubusercontent.com/assets/237260/5831005/23dfd8dc-a0de-11e4-8e0c-ccc77fc159ee.png)

![screenshot 2015-01-20 19 50 53](https://cloud.githubusercontent.com/assets/237260/5830989/cc31ef8a-a0dd-11e4-94ba-ceb084040892.png)

**Comment by madhums** [comment]
You need to set the heroku config vars

```
heroku config:set NODE_PATH=./config:./app/controllers
```

> If you are using heroku checkout how environment variables are set here.
