### ISSUE TITLE
AuthToken isn't saving for Facebook

### ISSUE THREAD

**Issue by dennismonsewicz** [madhums/node-express-mongoose-demo#131]
I am using this example app as a way to test authentication with Facebook for my application but the authToken isn't saving to the Mongo instance. It's saving out as a blank string

**Comment by anasbud** [comment]
Same here. Not sure if it's really used somethere though

**Comment by fourpixels** [comment]
It's not saved as there is no actual code to make that work. I guess if you need it you should save it yourself, but I would highly recommend you don't (first because it expires after time, and second because if someone else got it, he will be able to make bad things with it :))
