### ISSUE TITLE
[Error: failed to connect to [localhost:27017]]

### ISSUE THREAD

**Issue by dgsunesen** [madhums/node-express-mongoose-demo#132]
Hi guys,

So I just tried to get this machine running. But I keep getting this error all the time when I do npm start. As for client_id's and secret's... Is it possible to just put in dummy values?

The thing is, I just want to test it out without having to put in real ones.

Thanks guys.

**Comment by fyyyyy** [comment]
looks like your mongod isnt running

**Comment by chinmayrane** [comment]
Yes, looks like your `mongod` isn't running
Just use the Local Strategy for now if you don't want to get into `Google OAuth`, `Facebook`, `Twitter Login`.
