### ISSUE TITLE
NODE_PATH not recognized at npm start

### ISSUE THREAD

**Issue by josecarneiro** [madhums/node-express-mongoose-demo#133]
As insctructed, I cloned from git and installed the dependencies through `npm install`. Running 'npm start' gets me this error, every time. It somehow seems to take NODE_PATH as a command and not a variable. I'm running Windows 7.

```
$ npm start

> nodejs-express-mongoose-demo@4.0.0 start c:\development\node-express-mongoose-
demo
> NODE_PATH=./config:./app/controllers NODE_ENV=development ./node_modules/.bin/
nodemon server.js

'NODE_PATH' não é reconhecido como um comando interno ou externo,
programa operacional ou ficheiro batch.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.10.35
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! nodejs-express-mongoose-demo@4.0.0 start: `NODE_PATH=./config:./app/con
trollers NODE_ENV=development ./node_modules/.bin/nodemon server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejs-express-mongoose-demo@4.0.0 start script 'NODE_PAT
H=./config:./app/controllers NODE_ENV=development ./node_modules/.bin/nodemon se
rver.js'.
npm ERR! This is most likely a problem with the nodejs-express-mongoose-demo pac
kage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_PATH=./config:./app/controllers NODE_ENV=development ./node_mo
dules/.bin/nodemon server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodejs-express-mongoose-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\development\node-express-mongoose-demo\npm-debug.log
```

PS: The eight line reads in portuguese "'NODE_PATH' is not recognized as an internal or external command, operational program or batch file".

**Comment by chinmayrane** [comment]
This means, You've to set the Environment Path, the syntax given here is for UNIXy systems. While on Windows You have to separately edit by accessing the environment variables. 

A shorter route will be just deleting everything about node path and keeping it npm start as just 
node server.js  or node app.js

Try creating NODE_PATH environment on Windows System and assign it a value. But definitely, you can't set it via a script on Windows.

**Comment by josecarneiro** [comment]
Just setting the script to "node server.js" or "server.js" won't work. What value should I assign to NODE_PATH on Windows System?

**Comment by zbjornson** [comment]
Actually you can set NODE_PATH via script on Windows. Windows uses semicolons instead of colons to delimit folders. Depending on what shell you're using (powershell, command, node.js shell, etc.) there are different ways to set environment variables, however.

**Comment by zbjornson** [comment]
... actual recommendation there was to edit package.json's "script" parameters to change the colons to semicolons.

I'd also suggest to @madhums to use `path.join` instead of things like `__dirname + '/app/models'`. While Windows generally tolerates `/`, using `path.join` is OS-insensitive.

**Comment by YuliBlanco** [comment]
Hi! is there somebody here? I have the same problem, i use windows too, this is the line in my package.json  "build-js": "NOTE_PATH=./node_modules browserify -t [ babelify --presets [ es2015 ] ]  src/otro.js > public/app.js" but in my cmd the error is that note_path is not a recognized as an internal or external command... My questions is what can i use in my package.json that it will work same? because Note_path is not recognized by windows. Thanks!

**Comment by zbjornson** [comment]
There is no cross-platform/cross-shell way to set environment variables in a package.json file. It's better to do it inside a node.js file with `process.env.FOO="bar"`, unless you're okay with your method only working with one platform/shell and use that specific method (e.g. `$env:NODE_ENV="foo"` for powershell, `set NODE_ENV="foo"` for cmd, `NODE_ENV="foo"` for unixy).

(You also have NOTE_PATH, which is maybe supposed to be NODE_PATH.)

**Comment by madhums** [comment]
Take a look at [cross-env](https://www.npmjs.com/package/cross-env)

**Comment by sfranchi** [comment]
@madhums cross-env saved my life on Windows... Thanks! :)
