### ISSUE TITLE
AWS Deploy URL

### ISSUE THREAD

**Issue by chinmayrane** [madhums/node-express-mongoose-demo#134]
Can I extend the `Node_Env` deafault `URL` Concept to deploy Similar `Stack` Project to `AWS Beanstalk`?

The URL Messes up and gives me a `ERR_CONNECTION_TIMED_OUT`

What's the basic Configuration on a Server Level Deployment? And does the Node Environment depends on the URL to point to in AWS?

How should one make it run pointing to the default  `URL` used by `AWS Elastic Beanstalk`?

**Comment by madhums** [comment]
I don't completely what you want. Have you tried asking it in their [forums](https://forums.aws.amazon.com/forum.jspa?forumID=86)?

**Comment by chinmayrane** [comment]
Apologies, 

I figured it out long back. It's to be done via the config Amazon Beanstalk file. But It's better if we go to the AWS EC2 Platform. it's much Easier. Thanks a ton,

Cheers,
