### ISSUE TITLE
Cannot read property 'db' of undefined

### ISSUE THREAD

**Issue by jyanchen** [madhums/node-express-mongoose-demo#139]
I can't solve this problem. hope you can fix it for me.thanks.
this is error message:
![image](https://cloud.githubusercontent.com/assets/6831408/8519589/4a70cf82-2406-11e5-9e39-dd28be9f10a3.png)

I have already set the NODE_PATH on  my win7.

**Comment by madhums** [comment]
Looks like an issue with `NODE_PATH`
