### ISSUE TITLE
Cannot set cookie max age

### ISSUE THREAD

**Issue by LucidityDesign** [madhums/node-express-mongoose-demo#140]
I cannot set a maxAge for the cookies. I modified the code like this:

```
app.use(session({
    cookie: {
        path: '/',
        httpOnly: true,
        secure: false,
        maxAge: 360000
    },
    resave: true,
    saveUninitialized: true,
    secret: 'superSecret',
    store: new mongoStore({
        url: config.db,
        collection: 'sessions'
    })
}));
```

but I still receive session cookies. I also modified the `cookieSession` part with no luck.

**Comment by madhums** [comment]
Fixed in https://github.com/madhums/node-express-mongoose-demo/commit/ae0f4d8a3fd278cc0b86d5c84aad960d76ff9328
