### ISSUE TITLE
Unable to run  （ npm start ）

### ISSUE THREAD

**Issue by wwb568109135** [madhums/node-express-mongoose-demo#142]
![npm start](https://cloud.githubusercontent.com/assets/5113679/9121182/4da5c21e-3cb3-11e5-8794-05e5884e1c73.jpg)

The development environment is:
window7 
nodejs v0.10.25

**Comment by madhums** [comment]
Looks like a node path issue in windows. https://github.com/madhums/node-express-mongoose-demo/search?q=node+path&type=Issues&utf8=%E2%9C%93

**Comment by 0532** [comment]
解决了吗 怎么设置的啊  @wwb568109135
