### ISSUE TITLE
App does not start

### ISSUE THREAD

**Issue by ANUPJHA** [madhums/node-express-mongoose-demo#150]
After installing all packages via 'npm install' startup fails without throwing any error.
npm start
No error message also.

**Comment by madhums** [comment]
Could you tell me what version of node are you using?

```
$ node -v
```

**Comment by ANUPJHA** [comment]
v4.2.2

**Comment by ANUPJHA** [comment]
It's Windows7 machine

**Comment by madhums** [comment]
Could you try on node 5.x?

**Comment by ANUPJHA** [comment]
Tried same thing. The problem is it does not throw any error!

**Comment by ANUPJHA** [comment]
I have the older repo which I downloaded a year back works smoothly.

**Comment by wenpq** [comment]
I got same problem npm start fielded without throwing any error message.

> nodejs-express-mongoose-demo@4.0.0 start /home/app/Desktop/node-express-mongoose-demo
> NODE_ENV=development ./node_modules/.bin/nodemon server.js

[nodemon] 1.8.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`

My Environment is CentOS6.7+node5.1.1+mongo3.0.7, It's too weird.

**Comment by panzhangwang** [comment]
Just remove "?replicaSet=rs0" from development.js in your local env for a try.

**Comment by ClaytonSmith** [comment]
I was having the same issue. I removed the "?replicaSet=rs0" in `config/env/development.js` and it works now. Why is this?
