### ISSUE TITLE
Unable to login after creating account

### ISSUE THREAD

**Issue by ClaytonSmith** [madhums/node-express-mongoose-demo#151]
If I create an account using the signup method and log out, I am unable to log in again using the same credentials. I receive the `"Invalid email or password"` error. 

The only modification I have made to the project was removing `"?replicaSet=rs0"` in `config/env/development.js` to solve [this](https://github.com/madhums/node-express-mongoose-demo/issues/150) issue.

**Comment by madhums** [comment]
That is weird! I just checked and its working fine for me. Can you give more details?

**Comment by madhums** [comment]
![gh-151](https://cloud.githubusercontent.com/assets/123815/12007913/a01d4f58-ac1b-11e5-9c41-40e159b9a0a1.gif)

**Comment by ClaytonSmith** [comment]
It looks like there was an issue with my instance of Mongo. ooops
