### ISSUE TITLE
Store images locally

### ISSUE THREAD

**Issue by skunkies** [madhums/node-express-mongoose-demo#152]
Hi,
I use your template for starting a small project but I am facing an issue regarding images.
I would like to store the images locally instead of Amazon S3.
What I need to change to do so?
Thank you for helping.

**Comment by madhums** [comment]
Simply change this line to https://github.com/madhums/node-express-mongoose-demo/blob/master/config/express.js#L16

```js
const upload = require('multer')({ dest: 'uploads/' });
```

Also checkout the examples of multer https://github.com/expressjs/multer
