### ISSUE TITLE
 NODE_ENV=development ./node_modules/.bin/nodemon server.js

### ISSUE THREAD

**Issue by fantasyKing** [madhums/node-express-mongoose-demo#153]
I run the project by npm start when I had run npm install.It shows 'the NODE ENV' not internal or external command, nor can run a program or batch file.

**Comment by MajorTomVa** [comment]
in Windows you need to change this line in package.json:
          "start": "./node_modules/.bin/nodemon server.js",
and at command prompt :  c:set NODE_ENV=development

**Comment by EnergeticPixels** [comment]
I had to do the same thing.  But I made my change a little more permanent, seeing that my development environment and my staging/production environments are two totally different animals.  If you wish to go this route, you will need to set that very same variable in your system settings (for windows only)  Control Panel -> System -> Advanced system settings -> Environment Variables "button".  I ended up putting the variable in both the user and system variables area (my day job runs some funny security settings)..

**Comment by arduino731** [comment]
I have same problem, which one the path you put Environment Variable C:\Program Files (x86)\nodejs\ and what else? 
@MajorTomVa  
I have edit line in package.json
"start": "./node_modules/.bin/nodemon server.js"
at command prompt : c:set NODE_ENV=development
it said "bash: c:set: command not found"
why its c:set?

**Comment by MajorTomVa** [comment]
Hi arduino;
   you don't type the c:.  this solution is for those who use Windows.  The command prompt is usually C:.  So, on Windows computer, you would type      set   NODE_ENV=development

sorry for the confusion :)
