### ISSUE TITLE
How can you access User model in other files without exporting?

### ISSUE THREAD

**Issue by segmentationfaulter** [madhums/node-express-mongoose-demo#155]
@madhums You put everything about `user` model in `root/app/models/user.js` and you didn't export anything from it, and then you use this user model at few other places like [here](https://github.com/madhums/node-express-mongoose-demo/blob/master/config/passport.js#L8). I can't understand how could you use `user` model in `root/config/passport.js` without exporting it from `root/app/models/user.js`, can you help me understand it please?

**Comment by madhums** [comment]
Models are stored in mongoose. So I use mongoose to get the models. For example, to get a user model

```
const mongosoe = require('mongoose')
const User = mongoose.model('User');
```
