### ISSUE TITLE
Every successful login from the same Twitter account gets separately saved in mongo

### ISSUE THREAD

**Issue by alexbudin** [madhums/node-express-mongoose-demo#158]
Seems that every time you logout and login (with the same twitter account), the users table instead of being updated, gets another entry.

How can this be prevented?

**Comment by alexbudin** [comment]
Found the problem, and i think this should be fixed here as well. Here is the solution:

in /config/passport/twitter.js

we have:

```
const options = {
      criteria: { 'twitter.id': profile.id }
    };
```

we just need to change that to: 

```
const options = {
      criteria: { 'username': profile.username }
    };
```

This will make sure that if someone logs in with the same username it wont be saved in the database every time, only once.

What i would also suggest @madhums is to include in the **user** model the following:

```
created_at: {type: Date, default: Date.now()},
updated_at: {type: Date, default: Date.now()}

```

and of course make the necessary changes in the strategies or models to update the **updated_at** value

**Comment by madhums** [comment]
Hi @alexbudin thanks for noticing and reporting the issue. Could you send a PR may be? (I don't have much time atm)

**Comment by InsomniacSabbir** [comment]
Can I work on this ? @alexbudin @madhums

**Comment by madhums** [comment]
This should be fixed now.
