### ISSUE TITLE
Jade -> Pug

### ISSUE THREAD

**Issue by gkoberger** [madhums/node-express-mongoose-demo#170]
So glad this is back on Jade :)

However, unfortunately, Jade is being renamed due to legal issues:

https://github.com/pugjs/pug/issues/2184

So, Jade will have a deprecation notice and will eventually stop working, unfortunately.

**Comment by madhums** [comment]
Yep, I noticed that. The package name pug is still in 2.x-alpha so I will wait until it's stable.
