### ISSUE TITLE
How ‘createPagination’ comes to be effective?

### ISSUE THREAD

**Issue by Lucas-Qi** [madhums/node-express-mongoose-demo#184]
I see ```createPagination ``` in views/articles/index.jade:

```
    - if (pages > 1)
      ul.pagination
        != createPagination(pages, page)
```

But I can not find ```createPagination ``` definition throughout the whole project, I want to ask where  ```createPagination ``` is defined and how it comes to be effective? Thanks.

**Comment by madhums** [comment]
It comes from the `view-helpers` middleware. 

https://github.com/madhums/node-express-mongoose-demo/blob/master/config/express.js#L103
https://github.com/madhums/node-view-helpers/blob/master/index.js#L84

**Comment by Lucas-Qi** [comment]
Thanks a lot. Great projject :100:
