### ISSUE TITLE
TypeError : OAuth2Strategy requires a clientID option

### ISSUE THREAD

**Issue by Hybueno09** [madhums/node-express-mongoose-demo#188]
After i git clone this repo to windows system and i had typied npm install,it occurs this problem, can u tell me why? thanks

**Comment by madhums** [comment]
It looks like you haven't performed the `cp .env.example .env` step

https://github.com/madhums/node-express-mongoose-demo#install

Please read the install instructions properly.

**Comment by Hybueno09** [comment]
Hello , i have a new problem . When i inputed  `npm test` ,the comman line information like this:
D:\dev\nginx\html\node-express-mongoose-demo\test\test-articles-create.js:13 
const { cleanup } = require( './helper' );
SynataxError : unexpected token {
what's this problem.thanks much.

**Comment by madhums** [comment]
What version of node.js are you using? 

If you are using node < 6, please try to upgrade to node 6+ or node [latest](https://nodejs.org/dist/v6.3.1/node-v6.3.1-x86.msi)

**Comment by Hybueno09** [comment]
Thanks so much. After i upgraded to node 6+, it works.
