### ISSUE TITLE
Session storage does not work

### ISSUE THREAD

**Issue by anthonygore** [madhums/node-express-mongoose-demo#198]
The duo of `connect-mongo` and `express-session` does not work. If you log in to the site you'll notice there is no entry in the `sessions` collection in mongo, and there is no `connect.sid` cookie stored by your browser.

If you remove `cookie-session` from Express it works fine. Not sure why both are used in this project anyway..?

**Comment by with0out** [comment]
yep, delete either of these two, the other would work fine, no idea why use both...

**Comment by JSandmark** [comment]
Thank you for your comment, removing cookie-session helped my problems why nothing was saved to sessions in MongoDB.
