### ISSUE TITLE
Deploying on Heroku?

### ISSUE THREAD

**Issue by iamwhitebox** [madhums/node-express-mongoose-demo#203]
Has anyone had success deploying to Heroku? I have made many attempts with no success.

**Comment by gkoberger** [comment]
This isn't helpful, however it's always worked like a charm for me! What errors are you getting?

**Comment by iamwhitebox** [comment]
Many many issues, and it is very helpful because the question pertains to tools like Docker, and Dokku which automate deployment tasks.

I'll let you know if I can get it working successfully.

**Comment by madhums** [comment]
What issues are you having? If you simply follow the readme it must work. On top of it you can refer  https://devcenter.heroku.com/articles/getting-started-with-nodejs#deploy-the-app and don't forget to set ENV variables given in `.env.example` file
