### ISSUE TITLE
Issues with Imager (rackspace)

### ISSUE THREAD

**Issue by iamwhitebox** [madhums/node-express-mongoose-demo#204]
I have had multiple errors while using Imager, in fact I have never successfully uploaded an image to S3 or Rackspace with Imager.

This probably belongs in Imager issues but it does not look like much response is happening over there.

Anyone recommend another imaging library or a solution?

**Comment by madhums** [comment]
I must say I haven't maintained imager. I would suggest to look into `pkgcloud`
