### ISSUE TITLE
NPM install showed some outdated dependencies

### ISSUE THREAD

**Issue by jtbarker** [madhums/node-express-mongoose-demo#206]
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated jade@0.35.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by madhums** [comment]
Pug is still in beta. https://github.com/madhums/node-express-mongoose-demo/issues/170

About the rest, looks like they are deps of deps. Perhaps create an issue in the particular dependency repo?
