### ISSUE TITLE
bcrypt instead of crypto

### ISSUE THREAD

**Issue by juanda99** [madhums/node-express-mongoose-demo#214]
It would be better to use bcrypt, beause its more secure as it's slower (uses more computing cycles).
Your code could also be  better:

You wouldn't need salt field in User model, because it's saved into the same field as password does. 

For authentication, something like:

```
var mongoose = require('mongoose'),
  bcrypt = require('bcryptjs');

var userSchema = mongoose.Schema({
  email: String,
  pw: String,
});

userSchema.methods.validPassword = function(password) {
  return bcrypt.compareSync(password, this.pw);
}; 
```

I can make a PR

**Comment by PazzaVlad** [comment]
+1

**Comment by madhums** [comment]
+1 for `bcrypt`!

**Comment by Husamui** [comment]
+1

**Comment by mylastore** [comment]
please +1
