### ISSUE TITLE
Update to pug and new syntax?

### ISSUE THREAD

**Issue by TeddySmoker** [madhums/node-express-mongoose-demo#229]
Hello, as you might already know Jade changed it's name to Pug and they're currently at version 2.0.0-beta6. 
With the name change there have also been some syntax changed (ex: dashes are no more required for if/for/each statements). 

Do you plan on updating the project with these updates? If yes, may I do a PR?

**Comment by madhums** [comment]
Yes I plan to update it once a stable version is released. 

Closing this and keeping track in #170
