### ISSUE TITLE
Google signIn Not Working

### ISSUE THREAD

**Issue by madhavi007** [madhums/node-express-mongoose-demo#303]

**Comment by pradeep40423** [comment]
You have to provide the valid google api in .env file. So that it will work.

**Comment by madhavi007** [comment]
I already did but still not working.

**Comment by pradeep40423** [comment]
I will tell you the steps to integrate it. Give me some times.

**Comment by madhums** [comment]
1. Make sure to create a project on google developer console and use the correct keys/secret in `.env` file.
2. Make sure you have specified the callback url correctly (as what you have provided in the passport config)
  
    <img width="625" alt="Screenshot 2019-03-13 at 18 27 27" src="https://user-images.githubusercontent.com/123815/54300788-e2570500-45bd-11e9-8cd1-e3ba5e500c2c.png">

3. Checkout how to configure passport https://github.com/jaredhanson/passport-google-oauth

Google auth should be working fine https://nodejs-express-demo.herokuapp.com/
