### ISSUE TITLE
Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by payamrafiee** [madhums/node-express-mongoose-demo#323]
after installing dependencies and set .env I run npm start and I got this error:

`Cannot read property 'on' of undefined`
`(/node-express-mongoose-demo/server.js:43:3)`

**Comment by krupanand-shetty** [comment]
Just downgrade the version of mongoose back to 4.13.14.

**Comment by madhums** [comment]
https://github.com/madhums/node-express-mongoose-demo/issues/338#issuecomment-471781726
