### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined in server.js file

### ISSUE THREAD

**Issue by lumos102** [madhums/node-express-mongoose-demo#338]
when I run **npm** start after **cp .env.example .env**, it shows: TypeError: Cannot read property 'on' of undefined in server.js file(line 43)

**Comment by sanchit94** [comment]
Ran into the same error. I guess mongoose API has changed, so the connection property is now in the mongoose object. Essentially, this is how the `connect()` function in server.js should look like now

```
function connect () {
  var options = { server: { socketOptions: { keepAlive: 1 } } };
  mongoose.connect(config.db, options);
  return mongoose.connection;
}
```

**Comment by madhums** [comment]
Hi, sorry for the late response. This should be fixed now. Also note that `keepAlive` is not nested anymore. https://github.com/madhums/node-express-mongoose-demo/commit/642fba22caa172f3967e23662425b623a5b84380#diff-78c12f5adc1848d13b1c6f07055d996e
