### ISSUE TITLE
Users with Multiple Social Accounts, how to handle?

### ISSUE THREAD

**Issue by mspanish** [madhums/node-express-mongoose-demo#43]
This is one reason I've looked at Singly.com, which I think helps tie all of the user's different accounts together, although I haven't gotten that deep into the passport/node GitHub example, which doesn't use a DB but is only for authentication. 

Would doing that with this app be possible? It's easy for users to forget which account they signed in with last time, and then they create a whole new account, and get frustrated at the fact that all the information they saved is gone(I'm developing an elearning app so they are saving all their data to the db).

I'll take another look at the singly example, and see if I could integrate it in this app - but this is way beyond my current js coding abilities!

**Comment by madhums** [comment]
It's as simple as adding `passport-singly` just like twitter or google (which is already in the repo.
