### ISSUE TITLE
Add "Forgot Password"  to email your with a temporary link to reset password

### ISSUE THREAD

**Issue by amirmog** [madhums/node-express-mongoose-demo#82]
Feature request:

Please 
- add "Forgot Password"  (at the time of login) to email user with a temporary link to reset password.
- add a feature where user can change their password from a link in their profile

Some random resources which hopefully may help:

https://groups.google.com/forum/#!topic/nodejs/SAl5F8qInfA

http://stackoverflow.com/questions/17828663/passport-local-mongoose-change-password

https://github.com/substack/node-password-reset

https://github.com/jaredhanson/passport-local

https://github.com/braitsch/node-login

https://github.com/markbao/speakeasy

**Comment by skunkies** [comment]
+1
nice suggestion

**Comment by tarkanlar** [comment]
+1

**Comment by madhums** [comment]
I created a gist, hope this helps! https://gist.github.com/madhums/bab8ba69c9176b98580c39d5183c99c7
